#!/usr/bin/env python3

from mpi4py import MPI
from HopDec.HopDec import mainCMD
from HopDec.Utilities import printConsoleHeader, printConsoleFooter

if __name__ == "__main__":

    MPI.pickle.THRESHOLD = 0
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    if rank == 0:
        printConsoleHeader()

    mainCMD(comm)

    comm.barrier()
    if rank == 0:
        printConsoleFooter()

    MPI.Finalize()
